import re

def validate_response_format(output: str) -> bool:
    """
    Validate that the output contains the <response> tag and essential fields.

    Args:
        output (str): The output generated by the agent.

    Returns:
        bool: True if output passes all validations, False otherwise.
    """
    # Step 1: 检查 <response>...</response> 是否存在
    match = re.search(r"<response>(.*?)</response>", output, re.DOTALL)
    if not match:
        print("❌ Validation failed: Missing <response> tag.")
        return False

    # Step 2: 检查 response 内部内容是否包含关键字段
    response_content = match.group(1).lower()  # 转成小写，方便匹配

    missing_fields = []
    required_fields = ["task", "time", "people"]
    for field in required_fields:
        if field not in response_content:
            missing_fields.append(field)

    if missing_fields:
        print(f"❌ Validation failed: Missing required fields: {', '.join(missing_fields)}")
        return False

    # 都通过
    return True

import re

def detect_conflict_across_agents(outputs: dict) -> str:
    """
    简单冲突检测逻辑：如果两个 agent 在相同时间涉及相同的人，则视为冲突。

    Args:
        outputs (dict): agent_name -> output_str（包含 <response> 标签）

    Returns:
        str: 冲突信息描述
    """
    schedule = {}

    for agent, output in outputs.items():
        match = re.search(r"<response>.*?<task>(.*?)</task>.*?<time>(.*?)</time>.*?<people>(.*?)</people>.*?</response>", output, re.DOTALL)
        if not match:
            continue

        task, time, people = match.groups()
        time = time.strip()
        for person in people.split(","):
            person = person.strip()
            key = (time, person)
            if key in schedule:
                return f"🚨 Conflict Detected: {person} appears in multiple agents at {time}."
            schedule[key] = agent

    return "✅ No conflict detected."



